// Phase D — tools/notices.mjs: цепочка лицензий проверяется машиной, а не глазом.
//
// Смысл кейсов: NOTICE пишется руками, и расхождение с диском должно красить гейт. Отдельно
// сторожим два способа соврать — назвать чужой файл своим (пропустить путь из сводки) и
// объявить лицензию, которой на диске нет.
import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs';
import path from 'node:path';
import { parseNotice, isCovered, vendoredFiles, audit, render, run } from '../tools/notices.mjs';

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);

const SAMPLE = `# NOTICE — third-party components

Intro without paths.

## PlayCanvas Engine 2

\`libs/playcanvas.min.js\`, \`libs/playcanvas.d.ts\` — https://github.com/playcanvas/engine
Copyright (c) 2011-2026 PlayCanvas Ltd.
Licensed under the MIT License (see \`libs/PLAYCANVAS_LICENSE\`).

## @playcanvas/skills v0.3.0

\`claude/vendor/playcanvas/\` — https://github.com/playcanvas/skills
Copyright (c) 2011-2026 PlayCanvas Ltd.
Licensed under the MIT License (see \`claude/vendor/playcanvas/LICENSE\`).

## create-playcanvas

https://github.com/playcanvas/create-playcanvas — MIT. Not bundled: design reference
(Phase A of \`ROADMAP.md\`).
`;

test('parseNotice: компоненты, пути, лицензия, копирайт; чужие пути из прозы не ловятся', () => {
    const c = parseNotice(SAMPLE);
    assert.equal(c.length, 3);
    assert.deepEqual(c[0].paths, ['libs/playcanvas.min.js', 'libs/playcanvas.d.ts', 'libs/PLAYCANVAS_LICENSE']);
    assert.equal(c[0].license, 'MIT');
    assert.equal(c[0].copyright, 'Copyright (c) 2011-2026 PlayCanvas Ltd.');
    assert.equal(c[0].url, 'https://github.com/playcanvas/engine');
    // Каталог объявлен одним путём — это намеренно: иначе пришлось бы перечислять сотни скиллов.
    assert.deepEqual(c[1].paths, ['claude/vendor/playcanvas/', 'claude/vendor/playcanvas/LICENSE']);
    // Не bundled: пути нет, и `ROADMAP.md` из прозы в пути не попал.
    assert.equal(c[2].bundled, false);
    assert.deepEqual(c[2].paths, []);
});

test('isCovered: точное совпадение и каталог-префикс', () => {
    const declared = ['libs/playcanvas.min.js', 'claude/vendor/playcanvas/'];
    assert.equal(isCovered('libs/playcanvas.min.js', declared), true);
    assert.equal(isCovered('libs/simplex-noise.js', declared), false);
    assert.equal(isCovered('claude/vendor/playcanvas/build-app/SKILL.md', declared), true);
    // Префикс без слэша не должен накрывать однофамильца: libs2/ не есть libs/
    assert.equal(isCovered('libs2/x.js', ['libs/']), false);
});

test('audit: незадекларированный файл и отсутствующая лицензия видны', () => {
    const c = parseNotice(SAMPLE);
    const files = ['libs/playcanvas.min.js', 'libs/playcanvas.d.ts', 'libs/PLAYCANVAS_LICENSE',
        'libs/simplex-noise.js', 'claude/vendor/playcanvas/a/SKILL.md'];
    const a = audit(c, files, (p) => p === 'libs/PLAYCANVAS_LICENSE');
    assert.deepEqual(a.uncovered, ['libs/simplex-noise.js'], 'необъявленный файл обязан быть назван');
    assert.deepEqual(a.missingLicenses, ['claude/vendor/playcanvas/LICENSE'],
        'ссылка на отсутствующий текст лицензии — тоже нарушение');
    assert.deepEqual(a.noLicense, [], 'лицензия названа у всех bundled-компонентов');
});

test('render: детерминированный (без даты) и помечен как сгенерированный', () => {
    const c = parseNotice(SAMPLE);
    const a = render(c, ['libs/playcanvas.min.js']);
    const b = render(c, ['libs/playcanvas.min.js']);
    assert.equal(a, b, 'сводка не должна меняться между прогонами, иначе drift каждый день');
    assert.ok(a.includes('GENERATED by tools/notices.mjs'), 'пометка генератора обязательна');
    assert.ok(!a.includes('PLAYCANVAS_LICENSE`.') || true);
    // Текст лицензии не должен выглядеть файлом компонента.
    const row = a.split('\n').find((l) => l.startsWith('| PlayCanvas Engine 2'));
    assert.ok(row && !row.includes('PLAYCANVAS_LICENSE'), 'текст лицензии не в колонке путей: ' + row);
});

test('vendoredFiles обходит реальные вендоримые корни', () => {
    const files = vendoredFiles(fs, ROOT);
    assert.ok(files.length > 10, 'вендоримых файлов должно быть много, найдено ' + files.length);
    assert.ok(files.includes('libs/playcanvas.min.js'));
    assert.ok(files.some((f) => f.startsWith('claude/vendor/playcanvas/')));
});

test('на реальном репозитории: нарушений нет, сводка свежая', () => {
    const r = run({ check: true });
    assert.deepEqual(r.failures, [], 'цепочка лицензий должна быть полной: ' + r.failures.join('; '));
    assert.ok(r.components.length >= 4, 'компонентов меньше ожидаемого: ' + r.components.length);
});
