// Variants.js — GENERATED by tools/variants.mjs — do not edit by hand.
// The Master Project and its visual variants as the runtime reads them (no fetch, no build
// step). Canon: js/GameSpec.js (the shared game model) + presentation/variants/*.json (one
// file per variant) + presentation/mappings/*.json + presentation/presets/*.json.
// A variant is CONFIGURATION, never a copy: every entry presents the same GAME_SPEC.
/** @satisfies {Record<string, any>} */
const PROJECT_VARIANTS = {
    "project": {
        "id": "arcengine-sample",
        "name": "ArcEngine Sample",
        "kit": "ArcEngine",
        "version": "0.1.0",
        "schemaVersion": 1,
        "defaultVariant": "arcengine-sample-lowpoly3d",
        "profiles": [
            "2d",
            "2.5d",
            "isometric3d",
            "lowpoly3d",
            "full3d"
        ],
        "variants": [
            "arcengine-sample-2.5d",
            "arcengine-sample-2d",
            "arcengine-sample-full3d",
            "arcengine-sample-isometric3d",
            "arcengine-sample-lowpoly3d"
        ],
        "variantFiles": {
            "arcengine-sample-2.5d": "presentation/variants/arcengine-sample-2.5d.json",
            "arcengine-sample-2d": "presentation/variants/arcengine-sample-2d.json",
            "arcengine-sample-full3d": "presentation/variants/arcengine-sample-full3d.json",
            "arcengine-sample-isometric3d": "presentation/variants/arcengine-sample-isometric3d.json",
            "arcengine-sample-lowpoly3d": "presentation/variants/arcengine-sample-lowpoly3d.json"
        },
        "gameModel": "js/GameSpec.js",
        "assetRegistry": "GAME_SPEC.assets + presentation/mappings/*.json",
        "runtime": {
            "entry": "js/presentation/Runtime.js (PlayArcRuntime.start)",
            "url": "/?project=arcengine-sample&variant=<variantId>",
            "cli": "node tools/arc.mjs run --variant <variantId>",
            "all": "node tools/arc.mjs run --all"
        },
        "shared": {
            "gameplay": "ONE Game Model for every variant: rules, systems, world, entities, progression, save schema",
            "entityIds": [
                "character",
                "mill"
            ],
            "scenes": [
                "gameplay",
                "main-menu",
                "map",
                "inventory"
            ]
        },
        "generated": "tools/variants.mjs from js/GameSpec.js + presentation/variants/*.json"
    },
    "variants": {
        "arcengine-sample-2.5d": {
            "id": "arcengine-sample-2.5d",
            "name": "ArcEngine Sample — Hybrid 2.5D",
            "profile": "2.5d",
            "enabled": true,
            "description": "2D characters in a 3D world: the hero keeps its sprite as a billboard, the mill and the ground are real 3D, the camera is a tilted orthographic one.",
            "createdBy": "author",
            "createdFrom": "arcengine-sample-2d",
            "camera": {
                "mode": "isometric",
                "follow": "character",
                "azimuthDeg": -90,
                "elevationDeg": 60,
                "orthoHeightPx": 420,
                "orbit": false
            },
            "lighting": {
                "preset": "stylized",
                "shadows": 1,
                "toon": 1,
                "ink": 1,
                "outline": 1
            },
            "materials": {
                "shading": "toon"
            },
            "environment": {
                "ground": "plane+sprites",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "hybrid"
            },
            "ui": {
                "space": "screen"
            },
            "audio": {
                "spatial": true
            },
            "visualMappings": "presentation/mappings/arcengine-sample-2.5d.json"
        },
        "arcengine-sample-2d": {
            "id": "arcengine-sample-2d",
            "name": "ArcEngine Sample — Pixel 2D",
            "profile": "2d",
            "enabled": true,
            "description": "Top-down pixel presentation of the same game: orthographic camera, flat ground, sprites for every entity, tiles for the logical map, no shading model.",
            "createdBy": "author",
            "createdFrom": "arcengine-sample-lowpoly3d",
            "camera": {
                "mode": "topdown",
                "follow": "character",
                "azimuthDeg": -90,
                "elevationDeg": 88,
                "orthoHeightPx": 360,
                "zoom": 1,
                "orbit": false
            },
            "lighting": {
                "preset": "flat",
                "shadows": 0,
                "toon": 0,
                "ink": 0,
                "outline": 0,
                "fog": 0
            },
            "materials": {
                "shading": "unlit"
            },
            "environment": {
                "ground": "tilemap",
                "flatten": 1,
                "tilePx": 64
            },
            "animation": {
                "style": "sprite-frames"
            },
            "ui": {
                "space": "screen",
                "pixelSnap": true
            },
            "audio": {
                "spatial": false
            },
            "visualMappings": "presentation/mappings/arcengine-sample-2d.json"
        },
        "arcengine-sample-full3d": {
            "id": "arcengine-sample-full3d",
            "name": "ArcEngine Sample — Cinematic 3D",
            "profile": "full3d",
            "enabled": true,
            "description": "The full stack: perspective third-person camera over the shoulder, smooth PBR shading, soft shadows, fog, spatial audio, skeletal animation.",
            "createdBy": "author",
            "createdFrom": "arcengine-sample-isometric3d",
            "camera": {
                "mode": "thirdPerson",
                "follow": "character",
                "azimuthDeg": -90,
                "elevationDeg": 15,
                "fovDeg": 52,
                "distance": 420,
                "orbit": true
            },
            "lighting": {
                "preset": "realistic",
                "shadows": 1,
                "toon": 0,
                "ink": 0,
                "outline": 0,
                "fog": 0.00032
            },
            "materials": {
                "shading": "pbr"
            },
            "environment": {
                "ground": "terrain",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "skeletal"
            },
            "ui": {
                "space": "screen",
                "worldSpace": true
            },
            "audio": {
                "spatial": true
            },
            "effects": {
                "postprocessing": "cinematic",
                "particles": 1000
            },
            "visualMappings": "presentation/mappings/arcengine-sample-full3d.json"
        },
        "arcengine-sample-isometric3d": {
            "id": "arcengine-sample-isometric3d",
            "name": "ArcEngine Sample — Isometric 3D",
            "profile": "isometric3d",
            "enabled": true,
            "description": "Diablo-like presentation: a fixed orthographic camera over real 3D geometry, models instead of sprites, stylized 3D lighting with crisp shadows.",
            "createdBy": "author",
            "createdFrom": "arcengine-sample-2.5d",
            "camera": {
                "mode": "isometric",
                "follow": "character",
                "azimuthDeg": -90,
                "elevationDeg": 55,
                "orthoHeightPx": 480,
                "orbit": false
            },
            "lighting": {
                "preset": "isometric",
                "shadows": 1,
                "toon": 1,
                "ink": 2,
                "outline": 2
            },
            "materials": {
                "shading": "toon"
            },
            "environment": {
                "ground": "3d-tiles",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "skeletal"
            },
            "ui": {
                "space": "screen"
            },
            "audio": {
                "spatial": true
            },
            "visualMappings": "presentation/mappings/arcengine-sample-isometric3d.json"
        },
        "arcengine-sample-lowpoly3d": {
            "id": "arcengine-sample-lowpoly3d",
            "name": "ArcEngine Sample — Stylized 3D",
            "profile": "lowpoly3d",
            "enabled": true,
            "description": "The kit's default look: perspective camera, toon bands, ink edges and silhouette outline, exactly as Constants.js authors it. This is project.json's defaultVariant.",
            "createdBy": "author",
            "createdFrom": null,
            "camera": {
                "mode": "orbit",
                "follow": null,
                "azimuthDeg": -90,
                "elevationDeg": 57,
                "orbit": true
            },
            "lighting": {
                "preset": "isometric",
                "toon": 1,
                "ink": 2,
                "outline": 2,
                "shadows": 1
            },
            "materials": {
                "shading": "toon"
            },
            "environment": {
                "ground": "low-poly-terrain",
                "flatten": 0
            },
            "animation": {
                "style": "skeletal"
            },
            "ui": {
                "space": "screen"
            },
            "audio": {
                "spatial": true
            },
            "visualMappings": "presentation/mappings/arcengine-sample-lowpoly3d.json"
        }
    },
    "mappings": {
        "arcengine-sample-2d": {
            "player.visual": {
                "2d": {
                    "type": "sprite",
                    "asset": "assets/visual/2d/player.png",
                    "generated": true
                }
            },
            "world.door.visual": {
                "2d": {
                    "type": "sprite",
                    "asset": "assets/visual/2d/tile-door.png",
                    "generated": true
                }
            },
            "world.loot.visual": {
                "2d": {
                    "type": "sprite",
                    "asset": "assets/visual/2d/tile-loot.png",
                    "generated": true
                }
            },
            "world.mill.visual": {
                "2d": {
                    "type": "sprite",
                    "asset": "assets/visual/2d/mill.png",
                    "generated": true
                }
            },
            "world.obstacle.visual": {
                "2d": {
                    "type": "sprite",
                    "asset": "assets/visual/2d/tile-rock.png",
                    "generated": true
                }
            },
            "world.wall.visual": {
                "2d": {
                    "type": "tile",
                    "asset": "assets/visual/2d/tile-wall.png",
                    "generated": true
                }
            },
            "world.water.visual": {
                "2d": {
                    "type": "tile",
                    "asset": "assets/visual/2d/tile-water.png",
                    "generated": true
                }
            }
        }
    },
    "presets": {
        "cinematic": {
            "id": "cinematic",
            "description": "A reusable over-the-shoulder look: lower camera, longer lens feel, realistic light, a little fog.",
            "camera": {
                "mode": "thirdPerson",
                "elevationDeg": 12,
                "distance": 520,
                "fovDeg": 46
            },
            "lighting": {
                "preset": "realistic",
                "fog": 0.0004,
                "sunIntensity": 1.05,
                "shadows": 1,
                "toon": 0
            },
            "effects": {
                "postprocessing": "cinematic"
            }
        },
        "pixel-topdown": {
            "id": "pixel-topdown",
            "description": "A reusable pixel-art top-down look: straight-down orthographic camera, flat light, crisp sprites.",
            "camera": {
                "mode": "topdown",
                "elevationDeg": 88,
                "orthoHeightPx": 360,
                "orbit": false
            },
            "lighting": {
                "preset": "flat",
                "shadows": 0,
                "toon": 0,
                "ink": 0,
                "outline": 0,
                "fog": 0
            },
            "environment": {
                "ground": "tilemap",
                "flatten": 1
            }
        }
    },
    "journal": [
        {
            "id": "mig-1",
            "from": "lowpoly3d",
            "to": "2d",
            "source": "arcengine-sample-lowpoly3d",
            "target": "arcengine-sample-2d",
            "profile": "2d",
            "timestamp": "2026-09-23T06:38:37.108Z",
            "status": "committed",
            "changes": [
                "camera",
                "rendering",
                "visual_assets",
                "lighting",
                "materials",
                "animation_representation",
                "world_presentation",
                "depth_model",
                "visual_effects"
            ],
            "preserved": [
                "gameplay",
                "entity_ids",
                "scene_ids",
                "world_logic",
                "logical_coordinates",
                "rules",
                "systems",
                "quests",
                "inventory",
                "combat",
                "economy",
                "progression",
                "ui_logic",
                "save_schema",
                "audio_cues",
                "input_actions"
            ],
            "assetsGenerated": [
                "assets/visual/2d/player.png",
                "assets/visual/2d/mill.png"
            ],
            "fallbacksUsed": [
                "player.visual",
                "world.mill.visual"
            ],
            "counts": {
                "entities": 2,
                "preserved": 2,
                "visualReplacements": 2,
                "missingAssets": 2,
                "fallbackGeometry": 0,
                "cameraChanges": 1,
                "lightingChanges": 1,
                "worldChanges": 1,
                "uiChanges": 0,
                "gameplayFilesChanged": 0
            },
            "preservedProof": {
                "ok": true,
                "failed": [],
                "gameplayHash": "47a8f91e",
                "saveSchemaHash": "9680ab49",
                "entityIds": 2,
                "entityIdsPreserved": true,
                "sceneIds": [
                    "gameplay",
                    "main-menu",
                    "map",
                    "inventory"
                ],
                "sceneIdsPreserved": true,
                "coordinatesPreserved": true,
                "rulesPreserved": true,
                "saveSchemaPreserved": true,
                "gameplayPreserved": true
            },
            "error": null,
            "rollbackAvailable": true,
            "ms": 27.22,
            "by": "cli"
        }
    ]
};
