#!/usr/bin/env node
// Phase D — сканер цепочки лицензий: NOTICE -> THIRD_PARTY_NOTICES.md + drift-проверка.
//
// Зачем. Набор публичный (MIT) и вендорит чужой код: движок PlayCanvas, скиллы
// @playcanvas/skills, simplex-noise. `NOTICE` пишется руками, и пока его читает человек,
// расхождение с диском никто не ловит. Агент добавляет `libs/foo.js` или новую папку в
// `claude/vendor/` — и набор уезжает в мир с неполной атрибуцией, тихо. Здесь это проверяет
// машина: незадекларированный файл красит гейт с точным путём.
//
// Что делает:
//   1. разбирает `NOTICE` на компоненты (`## Заголовок` + тело);
//   2. обходит ВЕНДОРИМЫЕ корни и требует, чтобы каждый файл был покрыт объявленным путём —
//      точным ИЛИ каталогом: «claude/vendor/playcanvas/» покрывает всё поддерево, иначе
//      сканер требовал бы перечислять сотни файлов скиллов;
//   3. проверяет, что каждый лицензионный файл, на который ссылается `NOTICE`, существует;
//   4. генерирует `THIRD_PARTY_NOTICES.md` — машиночитаемую сводку;
//   5. `--check`: незадекларированный файл, отсутствующая лицензия или устаревшая сводка
//      дают exit 1. Это тот же приём drift-проверки, что у sync-skills/manifest/render-profiles.
//
//     node tools/notices.mjs            // записать THIRD_PARTY_NOTICES.md
//     node tools/notices.mjs --check    // только проверить (это зовёт tools/check.mjs)
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const NOTICE = 'NOTICE';
const OUT = 'THIRD_PARTY_NOTICES.md';
// Корни, где лежит ЧУЖОЙ код. Всё остальное в репозитории — наше, под MIT из LICENSE.
const VENDORED = ['libs', 'claude/vendor'];
const GEN_MARK = '<!-- GENERATED by tools/notices.mjs — правьте канон (NOTICE), а не этот файл. -->';

// --- чистые части (их проверяет tests/notices.test.mjs) ----------------------------------

/** Разбор NOTICE на компоненты. Путь в обратных кавычках считается объявлением, только если
 *  он начинается с вендоримого корня: иначе в список попал бы `ROADMAP.md` из фразы
 *  «(Phase A of `ROADMAP.md`)». */
export function parseNotice(text, roots) {
    const R = roots || VENDORED;
    const out = [];
    let cur = null;
    for (const line of text.split('\n')) {
        const h = /^##\s+(.*)$/.exec(line);
        if (h) {
            cur = { name: h[1].trim(), body: [] };
            out.push(cur);
            continue;
        }
        if (cur) cur.body.push(line);
    }
    for (const c of out) {
        const body = c.body.join('\n');
        c.paths = [...body.matchAll(/`([^`]+)`/g)].map((m) => m[1])
            .filter((p) => R.some((r) => p === r || p.startsWith(r + '/')))
            .filter((p, i, a) => a.indexOf(p) === i);
        const u = /https?:\/\/[^\s—)]+/.exec(body);
        c.url = u ? u[0].replace(/[.,;]+$/, '') : null;
        const lic = /\b(MIT|Apache-2\.0|BSD-[23]-Clause|CC0(?:\s1\.0)?|CC-BY[-\s][\w.]+|ISC|Unlicense)\b/i.exec(body);
        c.license = lic ? lic[1].toUpperCase().replace(/\s+/g, ' ') : null;
        const cr = c.body.find((l) => /^\s*Copyright\b/i.test(l));
        c.copyright = cr ? cr.trim() : null;
        // Лицензионные файлы, на которые ссылается раздел (см. `libs/PLAYCANVAS_LICENSE`).
        c.licenseFiles = [...body.matchAll(/`([^`]+)`/g)].map((m) => m[1])
            .filter((p) => /license|notice/i.test(p) && !R.some((r) => p.startsWith(r + '/') && !/license|notice/i.test(p)));
        c.bundled = c.paths.length > 0;
        delete c.body;
    }
    return out;
}

/** Покрыт ли файл объявлениями. Точное совпадение или каталог-префикс («dir/»). */
export function isCovered(file, declared) {
    for (const d of declared) {
        if (d.endsWith('/')) { if (file.startsWith(d)) return true; }
        else if (file === d) return true;
    }
    return false;
}

/** Файлы вендоримых корней, относительные пути с «/». */
export function vendoredFiles(fsLike, root, roots) {
    const R = roots || VENDORED;
    const out = [];
    const walk = (dir) => {
        let entries;
        try { entries = fsLike.readdirSync(path.join(root, dir), { withFileTypes: true }); } catch { return; }
        for (const e of entries) {
            const rel = dir ? dir + '/' + e.name : e.name;
            if (e.isDirectory()) walk(rel);
            else if (e.isFile()) out.push(rel);
        }
    };
    for (const r of R) walk(r);
    return out.sort();
}

/** Сводка: что не покрыто, каких лицензий не хватает. Чистая функция — тесты гоняют её без диска. */
export function audit(components, files, exists) {
    const declared = components.flatMap((c) => c.paths);
    const uncovered = files.filter((f) => !isCovered(f, declared));
    const licenseRefs = components.flatMap((c) => c.licenseFiles)
        .filter((p, i, a) => a.indexOf(p) === i);
    const missingLicenses = licenseRefs.filter((p) => !exists(p));
    const noLicense = components.filter((c) => c.bundled && !c.license).map((c) => c.name);
    return { declared, uncovered, licenseRefs, missingLicenses, noLicense };
}

/** Текст THIRD_PARTY_NOTICES.md. Детерминированный: никакой даты, иначе drift каждый день. */
export function render(components, files) {
    const L = [];
    L.push(GEN_MARK);
    L.push('# Third-party notices');
    L.push('');
    L.push('Machine-readable roll-up of `NOTICE`. Do not edit: `node tools/notices.mjs` regenerates it,');
    L.push('and `node tools/check.mjs` fails when it drifts or when a vendored file is undeclared.');
    L.push('');
    L.push(`Vendored roots scanned: ${VENDORED.map((r) => '`' + r + '/`').join(', ')} — ${files.length} files.`);
    L.push('');
    L.push('| Component | License | Bundled | Paths | Source |');
    L.push('| --- | --- | --- | --- | --- |');
    // Текст лицензии — не «файл компонента»: в сводке он отдельно, иначе `PLAYCANVAS_LICENSE`
    // читается как часть движка. В покрытии (audit) он при этом остаётся объявленным путём.
    const code = (c) => c.paths.filter((p) => !/license|notice/i.test(p));
    for (const c of components) {
        const paths = code(c).length ? code(c).map((p) => '`' + p + '`').join(', ') : 'not bundled';
        L.push(`| ${c.name} | ${c.license || '—'} | ${code(c).length ? 'yes' : 'no'} | ${paths} | ${c.url || '—'} |`);
    }
    L.push('');
    for (const c of components) {
        L.push(`## ${c.name}`);
        L.push('');
        if (c.copyright) L.push(c.copyright);
        L.push(`License: ${c.license || 'not stated in NOTICE'}` + (c.url ? ` — ${c.url}` : '') + '.');
        const codePaths = c.paths.filter((p) => !/license|notice/i.test(p));
        if (codePaths.length) L.push('Bundled at: ' + codePaths.map((p) => '`' + p + '`').join(', ') + '.');
        else L.push('Not bundled (design reference only).');
        if (c.licenseFiles.length) L.push('License text: ' + c.licenseFiles.map((p) => '`' + p + '`').join(', ') + '.');
        L.push('');
    }
    return L.join('\n');
}

// --- прогон ------------------------------------------------------------------------------
const isMain = process.argv[1] && import.meta.url === url.pathToFileURL(path.resolve(process.argv[1])).href;
const CHECK = process.argv.includes('--check');

export function run(opts) {
    const o = opts || {};
    const read = o.read || ((rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8'));
    const exists = o.exists || ((rel) => fs.existsSync(path.join(ROOT, rel)));
    const noticeText = read(NOTICE);
    const components = parseNotice(noticeText);
    const files = vendoredFiles(fs, ROOT);
    const a = audit(components, files, exists);
    const text = render(components, files);
    const failures = [];
    for (const f of a.uncovered) failures.push('вендоримый файл не объявлен в NOTICE: ' + f);
    for (const m of a.missingLicenses) failures.push('NOTICE ссылается на отсутствующий лицензионный файл: ' + m);
    for (const n of a.noLicense) failures.push('в NOTICE у компонента «' + n + '» не названа лицензия');
    // Сводку сверяем только в режиме проверки: в режиме записи мы её только что создали,
    // и жаловаться на собственный результат — шум (первая версия именно так и делала).
    if (o.check !== undefined ? o.check : CHECK) {
        const prev = exists(OUT) ? read(OUT) : null;
        if (prev == null) failures.push('нет ' + OUT + ' — запустите node tools/notices.mjs');
        else if (prev !== text) failures.push(OUT + ' устарел — запустите node tools/notices.mjs');
    }
    return { components, files, audit: a, text, failures };
}

if (isMain) {
    const r = run();
    if (CHECK) {
        if (r.failures.length) {
            console.error('\n  notices: FAIL');
            for (const f of r.failures) console.error('   · ' + f);
            console.error('');
            process.exit(1);
        }
        console.log('notices: ok (' + r.components.length + ' компонентов, ' + r.files.length + ' вендоримых файлов, ' + OUT + ' свеж)');
    } else {
        fs.writeFileSync(path.join(ROOT, OUT), r.text);
        console.log('notices: записан ' + OUT + ' (' + r.components.length + ' компонентов, ' + r.files.length + ' вендоримых файлов)');
        if (r.failures.length) {
            console.error('');
            for (const f of r.failures) console.error('   · ' + f);
            process.exit(1);
        }
    }
}
